apiVersion: v2
name: thehive
description: "TheHive: security incident response for the masses. This chart is unofficial."
type: application
version: 1.0.1
appVersion: "4.1.23-1"
# This is for the networking.k8s.io/v1 API used by the Ingress. see #10
kubeVersion: '>=1.19.0'
sources:
  - https://github.com/TheHive-Project/TheHive
maintainers:
  - name: "Jared Jennings"
    email: "jjennings@fastmail.fm"
icon: http://thehive-project.org/assets/img/logos/thehive.svg
dependencies:
  - name: cassandra
    version: ~7.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: cassandra.enabled
