{{- if .Values.attachmentStorage.pvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "thehive.attachmentPVCName" . }}
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
spec:
  storageClassName: {{ default .Values.attachmentStorage.pvc.storageClass .Values.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.attachmentStorage.pvc.size }}
{{- else -}}
{{- fail "Attachment storage using other than a persistent volume claim is not yet supported by this chart." -}}
{{- end -}}
