{{- if ((.Capabilities.APIVersions.Has "elasticsearch.k8s.elastic.co/v1") | or .Values.ignoreMissingECK) -}}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "thehive.fullname" . }}
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
spec:
  version: {{ .Values.elasticsearch.version }}
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false

{{- else -}}
{{ fail "Need Elasticsearch Cloud on Kubernetes (ECK) installed. This is a cluster-wide decision. See <https://artifacthub.io/packages/helm/elastic/eck-operator>." }}
{{- end }}
