apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "thehive.externalCassandra.secretname" . }}
type: Opaque
stringData:
  cassandra-password: {{ .Values.externalCassandra.dbUser.password | default "" | quote }}
