{{- if .Values.elasticsearch.external.enabled }}
{{- if .Values.elasticsearch.tls }}
{{- if .Values.elasticsearch.caCertSecret }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "thehive.elasticCACertSecretName" . }}
  labels:
    {{- include "thehive.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.elasticsearch.caCertSecretKey | quote }}: {{ .Values.elasticsearch.caCert | quote }}
{{- end }}
{{- end }}
{{- end }}
