{{- if .Values.extraHiveConfigurations }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "thehive.extraconfigsecret" . | quote }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.extraHiveConfigurations }}
  {{ $k | quote }}: {{ $v | quote }}
  {{- end }}
{{- end }}
