---
{{- range .Values.trustRootCerts }}
{{- /* we have a length limit, and hopefully trusted CA
       certs are not maliciously constructed, so this is
       not an adversarial case */ -}}
{{ $shortsum := . | sha256sum | substr 0 10 }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ printf "%s-ca-%s" (include "thehive.fullname" $) $shortsum | quote }}
  labels:
    {{- include "thehive.labels" $ | nindent 4 }}
type: Opaque
stringData:
  "ca.crt": {{ . | quote }}
...
{{- end }}
